// demontracine versija
//#define DEMO_VERSION

// su hardlocku
//#define HARDLOCK

// medianiniai filtrai
#define MEDIAN_FILTER

// laplass filtrai
#define LAPLASS_FILTER

// vidurkinimo filtrai
#define AVERAGE_FILTER

// auksto daznio filtrai
#define HIGH_PASS_FILTER

// gradientiniai filtrai
//#define GRADIENT_FILTER

// robertso filtrai
#define ROBERTS_FILTER

// mano filtras
#define HISTO_REDUCE_FILTER

//
#define EDGE_DETECTION_FILTER

// be gale heapo tikrinimo
#define COMMERCIAL